{{- if .Values.namespace_create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "fluxargo-metahelm.namespace" . }}
  labels:
    {{- include "fluxargo-metahelm.labels" . | nindent 4 }}
{{- end -}}
