{{- if eq .Values.sourcetype "helmrepo" -}}
apiVersion: source.toolkit.fluxcd.io/{{ include "fluxargo-metahelm.flux_apiversion_helmrepository" . }}
kind: HelmRepository
metadata:
  name: {{ .Values.sourcerepo }}
  namespace: {{ include "fluxargo-metahelm.flux_repo_namespace" . }}
  labels:
    {{- include "fluxargo-metahelm.labels" . | nindent 4 }}
spec:
  provider: generic
  interval: {{ include "fluxargo-metahelm.flux_repo_interval" . }}
{{-   if .Values.flux_repo_timeout }}
  timeout: {{ include "fluxargo-metahelm.flux_repo_timeout" . }}
{{-   end }}
  url: {{ .Values.sourceurl }}
{{-   if .Values.flux_repo_proxySecretRef }}
  proxySecretRef:
{{ .Values.flux_repo_proxySecretRef | toYaml | indent 4 }}
{{-   end -}}
{{-   if .Values.flux_repo_secretRef }}
  secretRef:
{{ .Values.flux_repo_secretRef | toYaml | indent 4 }}
{{-   end -}}
{{- end -}}
