{{- if eq .Values.sourcetype "gitrepo" -}}
apiVersion: source.toolkit.fluxcd.io/{{ include "fluxargo-metahelm.flux_apiversion_gitrepository" . }}
kind: GitRepository
metadata:
  name: {{ .Values.sourcerepo }}
  namespace: {{ include "fluxargo-metahelm.flux_repo_namespace" . }}
  labels:
    {{- include "fluxargo-metahelm.labels" . | nindent 4 }}
spec:
  interval: {{ include "fluxargo-metahelm.flux_repo_interval" . }}
{{-   if .Values.flux_repo_timeout }}
  timeout: {{ .Values.flux_repo_timeout }}
{{-   end }}
  ref:
    {{ include "fluxargo-metahelm.flux_repo_gitreftype" . }}: {{ .Values.sourcerevision | quote }}
  url: {{ .Values.sourceurl }}
{{-   if .Values.flux_repo_proxySecretRef }}
  proxySecretRef:
{{ .Values.flux_repo_proxySecretRef | toYaml | indent 4 }}
{{-   end -}}
{{-   if .Values.flux_repo_secretRef }}
  secretRef:
{{ .Values.flux_repo_secretRef | toYaml | indent 4 }}
{{-   end -}}
{{- end -}}
