apiVersion: helm.toolkit.fluxcd.io/{{ include "fluxargo-metahelm.flux_apiversion_helmrelease" . }}
kind: HelmRelease
metadata:
  name: {{ include "fluxargo-metahelm.flux_name" . }}
  namespace: {{ include "fluxargo-metahelm.namespace.flux" . }}
  labels:
    {{- include "fluxargo-metahelm.labels" . | nindent 4 }}
spec:
  releaseName: {{ include "fluxargo-metahelm.flux_releasename" . }}
  targetNamespace: {{ include "fluxargo-metahelm.namespace.name" . }}
  interval: {{ include "fluxargo-metahelm.flux_release_interval" . }}
{{- if .Values.flux_release_timeout }}
  timeout: {{ .Values.flux_release_timeout }}
{{- end }}
  suspend: {{ include "fluxargo-metahelm.flux_release_suspend" . }}
{{- include "fluxargo-metahelm.flux_chart" . | nindent 2 -}}
{{- include "fluxargo-metahelm.flux_values" . | nindent 2 -}}
