{{- if .Values.create -}}
{{-   if eq .Values.type "gitrepo" -}}
apiVersion: source.toolkit.fluxcd.io/{{ include "repo.flux_apiversion_gitrepository" . }}
kind: GitRepository
metadata:
  name: {{ include "repo.name" . }}
  namespace: {{ include "repo.namespace" . }}
  labels:
    {{- include "repo.labels" . | nindent 4 }}
spec:
  interval: {{ include "repo.flux_interval" . }}
{{-     if .Values.flux_timeout }}
  timeout: {{ .Values.flux_timeout }}
{{-     end }}
  ref:
    {{ include "repo.flux_gitreftype" . }}: {{ .Values.revision | quote }}
  url: {{ .Values.url }}
{{-     if .Values.flux_proxySecretRef }}
  proxySecretRef:
{{ .Values.flux_proxySecretRef | toYaml | indent 4 }}
{{-     end -}}
{{-     if .Values.flux_secretRef }}
  secretRef:
{{ .Values.flux_secretRef | toYaml | indent 4 }}
{{-     end -}}
{{-   end -}}
{{- end -}}
