{{- if .Values.create -}}
{{-   if eq .Values.type "helmrepo" -}}
apiVersion: source.toolkit.fluxcd.io/{{ include "repo.flux_apiversion_helmrepository" . }}
kind: HelmRepository
metadata:
  name: {{ include "repo.name" . }}
  namespace: {{ include "repo.namespace" . }}
  labels:
    {{- include "repo.labels" . | nindent 4 }}
spec:
  provider: generic
  interval: {{ include "repo.flux_interval" . }}
{{-     if .Values.flux_timeout }}
  timeout: {{ include "repo.flux_timeout" . }}
{{-     end }}
  url: {{ .Values.url }}
{{-     if .Values.flux_proxySecretRef }}
  proxySecretRef:
{{ .Values.flux_proxySecretRef | toYaml | indent 4 }}
{{-     end -}}
{{-     if .Values.flux_secretRef }}
  secretRef:
{{ .Values.flux_secretRef | toYaml | indent 4 }}
{{-     end -}}
{{-   end -}}
{{- end -}}
